application: rollatoon
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon\.icon
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: _go_app
